Table users [headercolor: #6360f7] {
	id uuid [ pk, not null, unique ]
	name varchar(100)
	email varchar(150) [ unique ]
	created_at datetime
	update_at datetime
	"profile_image " varchar(255)
	"password_hash " varchar(255)
}

Table Grab [headercolor: #63ff63] {
	id uuid [ pk, not null ]
	company_name varchar(150)
	"registration_number " varchar(30)
	adress varchar(255)
	"commission_rate " decimal [ default: (5,2) ]
}

Table Rider [headercolor: #36e094] {
	id uuid [ pk, not null ]
	"user_id " uuid
	id_card_number varchar2(20)
	status varchar(20)
	total_rides int
	created_at datetime
}

Table RideRequest [headercolor: #42c96d] {
	id uuid [ pk, not null ]
	"user_id " uuid
	vehicle_type_id uuid
	pickup_lat decimal [ default: (9,6) ]
	pickup_lng decimal [ default: (9,6) ]
	pickup_address varchar(255)
	"dropoff_lat " decimal [ default: (9,6) ]
	dropoff_lng decimal [ default: (9,6) ]
	dropoff_address varchar(255)
	status varchar(20)
	requested_at datetime
}

Table RideHistory [headercolor: #0b8c52] {
	id uuid [ pk, not null, unique ]
	ride_request_id uuid
	user_id uuid
	rider_id uuid
	vehicle_id uuid
	"distance_km " decimal [ default: (6,2) ]
	"duration_min " int
	base_price decimal [ default: (10,2) ]
	final_price decimal [ default: (10,2) ]
	start_time datetime
	end_time datetime
	status varchar(20)
}

Table Review [headercolor: #07b5fa] {
	id uuid [ pk, not null ]
	ride_history_id uuid [ unique ]
	"rating " int
	comment text(65535)
	created_at datetime
}

Table "Payment History" [headercolor: #d60d0d] {
	id uuid [ pk, not null ]
	ride_history_id uuid
	payment_method_id uuid
	amount decimal [ default: (10,2) ]
	status varchar(20)
	paid_at datetime
}

Table "Payment Methods" [headercolor: #ff0a5c] {
	id uuid [ pk, not null ]
	user_id uuid
	type varchar(20)
	provider varchar(50)
	account_nimber varchar(30)
	"is_default " boolean
}

Table "Discount History" [headercolor: #cf11fa] {
	id uuid [ pk, not null ]
	payment_history_id uuid
	discount_id uuid
	discount_amount decimal [ default: (10,2) ]
	applied_at datetime
}

Table Discount [headercolor: #ee81fc] {
	id uuid [ pk, not null ]
	code varchar(30) [ unique ]
	"description " varchar(255)
	discount_type varchar(10)
	value decimal [ default: (10,2) ]
	" valid_from " date
	valid_to date
}

Table Vehicles [headercolor: #fce028] {
	id uuid [ pk, not null ]
	rider_id uuid
	vehicle_type_id uuid
	license_plate varchar(15) [ unique ]
	brand varchar(50)
	model varchar(50)
	color varchar(30)
	year int
	status varchar(20)
}

Table GovermentDocuments [headercolor: #ff6e3d] {
	id uuid [ pk, not null ]
	rider_id uuid
	document_type varchar(3)
	document_number varchar(30)
	file_url varchar(255)
	verification_status varchar(20)
	verified_at datetime
	expiry_date date
}

Table VechiclesTypes [headercolor: #d6c315] {
	id uuid [ pk, not null ]
	name varchar(50)
	description varchar(255)
	base_fare decimal [ default: (10,2) ]
	price_per_km decimal [ default: (10,2) ]
	capacity int
}

Table DistanceToPrice [headercolor: #175e7a] {
	id uuid [ pk, not null ]
	min_distance_km decimal [ default: (6,2) ]
	max_distance_km decimal [ default: (6,2) ]
	price_per_km decimal [ default: (10,2) ]
}

Table TimePriceMultiplier [headercolor: #175e7a] {
	id uuid [ pk, not null ]
	name varchar(50)
	"start_time " time
	"end_time   " time
	"multiplier " decimal [ default: (4,2) ]
}

Table "Audit Log" [headercolor: #175e7a] {
	id uuid [ pk, not null ]
	"table_name " varchar(50)
	"record_id  " uuid
	old_value text(65535)
	"new_value  " text(65535)
	"created_at " datetime
}

Table Phon_user [headercolor: #175e7a] {
	id uuid [ pk, not null ]
	user_id uuid
}

Ref "fk_Rider_user_id _users" {
	Rider."user_id " > users.id [ delete: no action, update: no action ]
}

Ref fk_GovermentDocuments_rider_id_Rider {
	GovermentDocuments.rider_id > Rider.id [ delete: no action, update: no action ]
}

Ref fk_Vehicles_rider_id_Rider {
	Vehicles.rider_id > Rider.id [ delete: no action, update: no action ]
}

Ref fk_Vehicles_vehicle_type_id_VechiclesTypes {
	Vehicles.vehicle_type_id > VechiclesTypes.id [ delete: no action, update: no action ]
}

Ref "fk_RideRequest_user_id _users" {
	RideRequest."user_id " > users.id [ delete: no action, update: no action ]
}

Ref fk_RideHistory_ride_request_id_RideRequest {
	RideHistory.ride_request_id > RideRequest.id [ delete: no action, update: no action ]
}

Ref fk_RideHistory_user_id_users {
	RideHistory.user_id > users.id [ delete: no action, update: no action ]
}

Ref fk_RideHistory_rider_id_Rider {
	RideHistory.rider_id > Rider.id [ delete: no action, update: no action ]
}

Ref fk_RideHistory_vehicle_id_Vehicles {
	RideHistory.vehicle_id > Vehicles.id [ delete: no action, update: no action ]
}

Ref "fk_users_id_Payment Methods" {
	users.id < "Payment Methods".user_id [ delete: no action, update: no action ]
}

Ref "fk_Payment History_ride_history_id_RideHistory" {
	"Payment History".ride_history_id > RideHistory.id [ delete: no action, update: no action ]
}

Ref "fk_Payment History_payment_method_id_Payment Methods" {
	"Payment History".payment_method_id > "Payment Methods".id [ delete: no action, update: no action ]
}

Ref "fk_Review_ride_history_id_Payment History" {
	Review.ride_history_id > "Payment History".id [ delete: no action, update: no action ]
}

Ref "fk_Discount History_payment_history_id_Payment History" {
	"Discount History".payment_history_id > "Payment History".id [ delete: no action, update: no action ]
}

Ref "fk_Discount History_discount_id_Discount" {
	"Discount History".discount_id > Discount.id [ delete: no action, update: no action ]
}

Ref fk_Phon_user_user_id_users {
	Phon_user.user_id > users.id [ delete: no action, update: no action ]
}