Table users [headercolor: #6360f7] {
	id uuid [ pk, not null, default: `UUIDV7()` ]
	name varchar(100) [ not null ]
	email varchar(150) [ not null, unique ]
	password_hash varchar(255) [ not null ]
	profile_image varchar(255) [ not null ]
	created_at timestamptz [ not null, default: `now()` ]
	update_at timestamptz [ not null, default: `now()` ]
}

Table Phone_user [headercolor: #175e7a] {
	id uuid [ pk, not null, default: `UUIDV7()` ]
	user_id uuid [ not null ]
	phone_number varchar(20) [ not null, unique ]
}

enum riderStatus {
	"ACTIVE" // คนขับพร้อมใช้งาน
	"INACTIVE" // คนขับไม่พร้อมใช้งาน
	"SUSPENDED" // คนขับถูกระงับการใช้งาน
}

Table Rider [headercolor: #36e094] {
	id uuid [ pk, not null, default: `UUIDV7()` ]
	user_id uuid [ not null, unique ]
	status riderStatus [ not null ]
	total_rides int [ not null ]
	created_at timestamptz [ not null, default: `now()` ]
}

enum RideStatus {
	"REQUESTED" // เรียกรถแล้ว
	"ACCEPTED" // คนขับรับงานแล้ว
	"IN_PROGRESS" // กำลังเดินทาง
	"COMPLETED" // เดินทางเสร็จสิ้น
	"CANCELLED" // ยกเลิกการเดินทาง
}

Table RideRequest [headercolor: #42c96d] {
	id uuid [ pk, not null, default: `UUIDV7()` ]
	user_id uuid [ not null ]
	vehicle_type_id uuid [ not null ]
	pickup_lat numeric(9,6) [ not null ]
	pickup_lng numeric(9,6) [ not null ]
	pickup_address varchar(255) [ not null ]
	dropoff_lat numeric(9,6) [ not null ]
	dropoff_lng numeric(9,6) [ not null ]
	dropoff_address varchar(255) [ not null ]
	status RideStatus [ not null ]
	requested_at timestamptz [ not null, default: `now()` ]
}

enum RideHistoryStatus {
	"COMPLETED" // การเดินทางเสร็จสิ้น
	"IN_PROGRESS" // การเดินทางกำลังดำเนินอยู่
	"CANCELLED" // การเดินทางถูกยกเลิก
}

Table RideHistory [headercolor: #0b8c52] {
	id uuid [ pk, not null, default: `UUIDV7()` ]
	ride_request_id uuid [ not null ]
	user_id uuid [ not null ]
	rider_id uuid [ not null ]
	vehicle_id uuid [ not null ]
	distance_km numeric(6,2) [ not null ]
	duration_min int [ not null ]
	base_price numeric(10,2) [ not null, check: `base_price > 0` ]
	final_price numeric(10,2) [ not null, check: `final_price > 0` ]
	start_time timestamptz [ not null, default: `now()` ]
	end_time timestamptz [ not null, default: `now()` ]
	status RideHistoryStatus [ not null ]
}

Table Review [headercolor: #07b5fa] {
	id uuid [ pk, not null, default: `UUIDV7()` ]
	ride_history_id uuid [ not null, unique ]
	// rating ต้องอยู่ระหว่าง 1 ถึง 5
	rating int [ not null, check: `rating >= 1 AND rating <= 5` ]
	// comment ต้องไม่ว่าง และมีความยาวไม่เกิน 255 ตัวอักษร
	comment varchar(255) [ not null ]
	created_at timestamptz [ not null, default: `now()` ]
}

enum paymentStatus {
	"PAID" // ชำระเงินแล้ว
	"PENDING" // รอดำเนินการชำระเงิน
	"FAILED" // การชำระเงินล้มเหลว
}

Table Payment_History [headercolor: #d60d0d] {
	id uuid [ pk, not null, default: `UUIDV7()` ]
	ride_history_id uuid [ not null ]
	payment_method_id uuid [ not null ]
	amount numeric(10,2) [ not null, check: `amount > 0` ]
	status paymentStatus [ not null, default: `PENDING` ]
	paid_at timestamptz [ not null, default: `now()` ]
}

Table Payment_Methods [headercolor: #ff0a5c] {
	id uuid [ pk, not null, default: `UUIDV7()` ]
	user_id uuid [ not null ]
	type varchar(20) [ not null ]
	provider varchar(50) [ not null ]
	account_number varchar(30) [ not null ]
	is_default boolean [ not null ]
}

Table Discount_History [headercolor: #cf11fa] {
	id uuid [ pk, not null, default: `UUIDV7()` ]
	payment_history_id uuid [ not null ]
	discount_id uuid [ not null ]
	discount_amount numeric(10,2) [ not null, check: `discount_amount > 0` ]
	applied_at timestamptz [ not null, default: `now()` ]
}

enum DiscountType {
	"PERCENTAGE" // ส่วนลดเป็นเปอร์เซ็นต์
	"FIXED" // ส่วนลดเป็นจำนวนเงินคงที่
}

Table Discount [headercolor: #ee81fc] {
	id uuid [ pk, not null, default: `UUIDV7()` ]
	code varchar(30) [ not null, unique ]
	description varchar(255) [ not null ]
	discount_type DiscountType [ not null ]
	value numeric(10,2) [ not null, check: `value > 0` ]
	valid_from timestamptz [ not null, default: `now()` ]
	valid_to timestamptz [ not null, default: `now()` ]

	check: {
		`valid_from < valid_to` // ตรวจสอบว่า valid_from ต้องน้อยกว่า valid_to
	}
}

enum VehicleStatus {
	"ACTIVE" // รถพร้อมใช้งาน
	"INACTIVE" // รถไม่พร้อมใช้งาน
	"MAINTENANCE" // รถอยู่ระหว่างการซ่อมบำรุง
}

Table Vehicles [headercolor: #fce028] {
	id uuid [ pk, not null, default: `UUIDV7()` ]
	rider_id uuid [ not null ]
	vehicle_type_id uuid [ not null ]
	license_plate varchar(15) [ not null, unique ]
	brand varchar(50) [ not null ]
	model varchar(50) [ not null ]
	color varchar(30) [ not null ]
	year int [ not null ]
	status VehicleStatus [ not null ]
}

enum DocumentType {
	"ID" // บัตรประชาชน
	"DL" // ใบขับขี่
}

enum VerificationStatus {
	"VERIFIED" // เอกสารได้รับการยืนยันแล้ว
	"PENDING" // เอกสารอยู่ระหว่างการตรวจสอบ
	"REJECTED" // เอกสารถูกปฏิเสธ
}

Table GovermentDocuments [headercolor: #ff6e3d] {
	id uuid [ pk, not null, default: `UUIDV7()` ]
	rider_id uuid [ not null ]
	document_type DocumentType [ not null ]
	document_number varchar(30) [ not null ]
	file_url varchar(255) [ not null ]
	verification_status VerificationStatus [ not null ]
	verified_at timestamptz [ not null, default: `now()` ]
	expiry_date date [ not null ]

	Indexes {
		(document_type, document_number) [ unique ]
	}
}


Table VehiclesTypes [headercolor: #d6c315] {
	id uuid [ pk, not null, default: `UUIDV7()` ]
	name varchar(50) [ not null, unique ]
	description varchar(255) [ not null ]
	base_fare numeric(10,2) [ not null ]
	price_per_km numeric(10,2) [ not null ]
	capacity int [ not null ]
}

Table DistanceToPrice [headercolor: #175e7a] {
	id uuid [ pk, not null, default: `UUIDV7()` ]
	min_distance_km numeric(6,2) [ not null ]
	max_distance_km numeric(6,2) [ not null ]
	price_per_km numeric(10,2) [ not null ]
}

Table TimePriceMultiplier [headercolor: #175e7a] {
	id uuid [ pk, not null, default: `UUIDV7()` ]
	name varchar(50) [ not null ]
	start_time time [ not null ]
	end_time time [ not null ]
	multiplier numeric(4,2) [ not null ]
}

Table Audit_Log [headercolor: #175e7a] {
	id uuid [ pk, not null, default: `UUIDV7()` ]
	table_name varchar(50) [ not null ]
	record_id uuid [ not null ]
	old_value text [ not null ]
	new_value text [ not null ]
	created_at timestamptz [ not null, default: `now()` ]
}

Ref fk_Rider_user_id_users {
	Rider.user_id - users.id [ delete: restrict, update: no action ]
}

Ref fk_GovermentDocuments_rider_id_Rider {
	GovermentDocuments.rider_id > Rider.id [ delete: restrict, update: no action ]
}

Ref fk_Vehicles_rider_id_Rider {
	Vehicles.rider_id > Rider.id [ delete: restrict, update: no action ]
}

Ref fk_Vehicles_vehicle_type_id_VehiclesTypes {
	Vehicles.vehicle_type_id > VehiclesTypes.id [ delete: restrict, update: no action ]
}

Ref fk_RideRequest_user_id_users {
	RideRequest.user_id > users.id [ delete: restrict, update: no action ]
}

Ref fk_RideHistory_ride_request_id_RideRequest {
	RideHistory.ride_request_id > RideRequest.id [ delete: restrict, update: no action ]
}

Ref fk_RideHistory_user_id_users {
	RideHistory.user_id > users.id [ delete: restrict, update: no action ]
}

Ref fk_RideHistory_rider_id_Rider {
	RideHistory.rider_id > Rider.id [ delete: restrict, update: no action ]
}

Ref fk_RideHistory_vehicle_id_Vehicles {
	RideHistory.vehicle_id > Vehicles.id [ delete: restrict, update: no action ]
}

Ref fk_users_id_Payment_Methods {
	users.id < Payment_Methods.user_id [ delete: restrict, update: no action ]
}


Ref fk_Payment_History_ride_history_id_RideHistory {
	Payment_History.ride_history_id > RideHistory.id [ delete: restrict, update: no action ]
}

Ref fk_Payment_History_payment_method_id_Payment_Methods {
	Payment_History.payment_method_id > Payment_Methods.id [ delete: restrict, update: no action ]
}

Ref fk_Review_ride_history_id_RideHistory {
	Review.ride_history_id > RideHistory.id [ delete: restrict, update: no action ]
}


Ref fk_Discount_History_payment_history_id_Payment_History {
	Discount_History.payment_history_id > Payment_History.id [ delete: restrict, update: no action ]
}

Ref fk_Discount_History_discount_id_Discount {
	Discount_History.discount_id > Discount.id [ delete: restrict, update: no action ]
}

Ref fk_Phone_user_user_id_users {
	Phone_user.user_id > users.id [ delete: restrict, update: no action ]
}